[package]
name = "merkle_patricia_tree"
version = "0.1.0"
authors = ["Andrii Kuz <ext-andrii.kuz@here.com>"]

[dependencies]
#TODO: investigate to use direct link to parity repo/utils/rlp
rlp = { path = "util/rlp" }
exonum_leveldb = "0.9.1"
ethereum-types = "0.2.3"